ALTER TABLE transactions
  ALTER COLUMN created_at TYPE TIMESTAMP
  USING created_at AT TIME ZONE 'UTC';

ALTER TABLE accounts
  ALTER COLUMN created_at TYPE TIMESTAMP
  USING created_at AT TIME ZONE 'UTC';

ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMP
  USING created_at AT TIME ZONE 'UTC';
