// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, user_id, currency, balance, created_at) 
VALUES ($1, $2, $3, $4, NOW()) 
RETURNING created_at
`

type CreateAccountParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Currency string      `db:"currency" json:"currency"`
	Balance  int64       `db:"balance" json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Currency,
		arg.Balance,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, role, created_at) 
VALUES ($1, $2, $3, $4, NOW()) 
RETURNING created_at
`

type CreateUserParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Username string      `db:"username" json:"username"`
	Email    string      `db:"email" json:"email"`
	Role     string      `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Role,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const deductLockedFunds = `-- name: DeductLockedFunds :execrows
UPDATE accounts
SET locked_micros = locked_micros - $1, balance = balance - $1
WHERE id = $2
`

type DeductLockedFundsParams struct {
	LockedMicros int64       `db:"locked_micros" json:"locked_micros"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) DeductLockedFunds(ctx context.Context, arg DeductLockedFundsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deductLockedFunds, arg.LockedMicros, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, currency, balance, created_at 
FROM accounts 
WHERE id = $1
`

type GetAccountRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Currency  string             `db:"currency" json:"currency"`
	Balance   int64              `db:"balance" json:"balance"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalanceAndLocked = `-- name: GetAccountBalanceAndLocked :one
SELECT balance, locked_micros, currency FROM accounts WHERE id = $1 FOR UPDATE
`

type GetAccountBalanceAndLockedRow struct {
	Balance      int64  `db:"balance" json:"balance"`
	LockedMicros int64  `db:"locked_micros" json:"locked_micros"`
	Currency     string `db:"currency" json:"currency"`
}

func (q *Queries) GetAccountBalanceAndLocked(ctx context.Context, id pgtype.UUID) (GetAccountBalanceAndLockedRow, error) {
	row := q.db.QueryRow(ctx, getAccountBalanceAndLocked, id)
	var i GetAccountBalanceAndLockedRow
	err := row.Scan(&i.Balance, &i.LockedMicros, &i.Currency)
	return i, err
}

const getEntries = `-- name: GetEntries :many
SELECT id, transaction_id, account_id, amount, direction, created_at
FROM entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetEntriesParams struct {
	AccountID pgtype.UUID `db:"account_id" json:"account_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetEntries(ctx context.Context, arg GetEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntries, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, role, created_at 
FROM users 
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const lockAccountFunds = `-- name: LockAccountFunds :execrows
UPDATE accounts
SET locked_micros = locked_micros + $1
WHERE id = $2
`

type LockAccountFundsParams struct {
	LockedMicros int64       `db:"locked_micros" json:"locked_micros"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) LockAccountFunds(ctx context.Context, arg LockAccountFundsParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockAccountFunds, arg.LockedMicros, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseAccountFunds = `-- name: ReleaseAccountFunds :execrows
UPDATE accounts
SET locked_micros = locked_micros - $1
WHERE id = $2
`

type ReleaseAccountFundsParams struct {
	LockedMicros int64       `db:"locked_micros" json:"locked_micros"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ReleaseAccountFunds(ctx context.Context, arg ReleaseAccountFundsParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseAccountFunds, arg.LockedMicros, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseAccountFundsSafe = `-- name: ReleaseAccountFundsSafe :execrows
UPDATE accounts
SET locked_micros = locked_micros - $1
WHERE id = $2 AND locked_micros >= $1
`

type ReleaseAccountFundsSafeParams struct {
	LockedMicros int64       `db:"locked_micros" json:"locked_micros"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ReleaseAccountFundsSafe(ctx context.Context, arg ReleaseAccountFundsSafeParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseAccountFundsSafe, arg.LockedMicros, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
