// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, user_id, currency, balance, created_at) 
VALUES ($1, $2, $3, $4, NOW()) 
RETURNING created_at
`

type CreateAccountParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Currency string      `db:"currency" json:"currency"`
	Balance  int64       `db:"balance" json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Currency,
		arg.Balance,
	)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, created_at) 
VALUES ($1, $2, $3, NOW()) 
RETURNING created_at
`

type CreateUserParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Username string      `db:"username" json:"username"`
	Email    string      `db:"email" json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username, arg.Email)
	var created_at pgtype.Timestamp
	err := row.Scan(&created_at)
	return created_at, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, currency, balance, created_at 
FROM accounts 
WHERE id = $1
`

type GetAccountRow struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	Currency  string           `db:"currency" json:"currency"`
	Balance   int64            `db:"balance" json:"balance"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getEntries = `-- name: GetEntries :many
SELECT id, transaction_id, account_id, amount, direction, created_at
FROM entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetEntriesParams struct {
	AccountID pgtype.UUID `db:"account_id" json:"account_id"`
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetEntries(ctx context.Context, arg GetEntriesParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, getEntries, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, created_at 
FROM users 
WHERE id = $1
`

type GetUserRow struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	Username  string           `db:"username" json:"username"`
	Email     string           `db:"email" json:"email"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
