// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditLogsByEntity = `-- name: GetAuditLogsByEntity :many
SELECT id, entity_type, entity_id, actor_id, action, prev_state, next_state, metadata, created_at
FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY id ASC
`

type GetAuditLogsByEntityParams struct {
	EntityType string      `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
}

func (q *Queries) GetAuditLogsByEntity(ctx context.Context, arg GetAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.Action,
			&i.PrevState,
			&i.NextState,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (
  entity_type,
  entity_id,
  actor_id,
  action,
  prev_state,
  next_state,
  metadata,
  created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id
`

type InsertAuditLogParams struct {
	EntityType string      `db:"entity_type" json:"entity_type"`
	EntityID   pgtype.UUID `db:"entity_id" json:"entity_id"`
	ActorID    pgtype.UUID `db:"actor_id" json:"actor_id"`
	Action     string      `db:"action" json:"action"`
	PrevState  *string     `db:"prev_state" json:"prev_state"`
	NextState  *string     `db:"next_state" json:"next_state"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.Action,
		arg.PrevState,
		arg.NextState,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
