// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package repository

import (
	"context"
)

const finalizeIdempotencyKey = `-- name: FinalizeIdempotencyKey :one
UPDATE idempotency_keys
SET response_status = $1,
    response_body = $2,
    content_type = $3,
    in_progress = FALSE,
    updated_at = NOW()
WHERE idempotency_key = $4 AND request_hash = $5
RETURNING idempotency_key, request_hash, response_status, response_body, content_type, in_progress
`

type FinalizeIdempotencyKeyParams struct {
	ResponseStatus int32  `db:"response_status" json:"response_status"`
	ResponseBody   []byte `db:"response_body" json:"response_body"`
	ContentType    string `db:"content_type" json:"content_type"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    string `db:"request_hash" json:"request_hash"`
}

type FinalizeIdempotencyKeyRow struct {
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    string `db:"request_hash" json:"request_hash"`
	ResponseStatus int32  `db:"response_status" json:"response_status"`
	ResponseBody   []byte `db:"response_body" json:"response_body"`
	ContentType    string `db:"content_type" json:"content_type"`
	InProgress     bool   `db:"in_progress" json:"in_progress"`
}

func (q *Queries) FinalizeIdempotencyKey(ctx context.Context, arg FinalizeIdempotencyKeyParams) (FinalizeIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, finalizeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ContentType,
		arg.IdempotencyKey,
		arg.RequestHash,
	)
	var i FinalizeIdempotencyKeyRow
	err := row.Scan(
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ContentType,
		&i.InProgress,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT idempotency_key, request_hash, response_status, response_body, content_type, in_progress
FROM idempotency_keys
WHERE idempotency_key = $1
`

type GetIdempotencyKeyRow struct {
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    string `db:"request_hash" json:"request_hash"`
	ResponseStatus int32  `db:"response_status" json:"response_status"`
	ResponseBody   []byte `db:"response_body" json:"response_body"`
	ContentType    string `db:"content_type" json:"content_type"`
	InProgress     bool   `db:"in_progress" json:"in_progress"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, idempotencyKey string) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, idempotencyKey)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ContentType,
		&i.InProgress,
	)
	return i, err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO idempotency_keys (idempotency_key, request_hash, method, path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING idempotency_key
`

type ReserveIdempotencyKeyParams struct {
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    string `db:"request_hash" json:"request_hash"`
	Method         string `db:"method" json:"method"`
	Path           string `db:"path" json:"path"`
}

func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.Method,
		arg.Path,
	)
	var idempotency_key string
	err := row.Scan(&idempotency_key)
	return idempotency_key, err
}
